### ISSUE TITLE
[add] Censo 2022 - 17 de Maio - Alfabetização: Resultados do universo

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#596]
**Arquiteturas**
- - [x] [Tabela 9542](https://docs.google.com/spreadsheets/d/1xImzomB7YKgFKRZETJ-9ZIHRnpW5HKuA/edit#gid=1045172528)  
- - [x] [Tabela 9543](https://docs.google.com/spreadsheets/d/1DOBk79PUsJkyfp42-v_pvzGGQ66cGCbn/edit#gid=1045172528)
- - [x] [Tabela 8180](https://docs.google.com/spreadsheets/d/1vQFvlt_PiuFuuc9LQOhF13h19LgpPbmu/edit#gid=1045172528)
- - [x] [Tabela 8181](https://docs.google.com/spreadsheets/d/1iSJHVFpwEKzdM9B5b9yQ915oHS10X_fv/edit#gid=1045172528)
## TODO
- [x] Download dos dados
- [ ] Subir metadados
- [x] Criar e validar modelos e testes
- [ ] Abrir PR em prod
- [x] Documentar a atualização dos dados do censo
